# Generated by Django 4.0.6 on 2022-11-19 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_app', '0002_delete_product_alter_menu_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='food',
            options={'verbose_name': 'Еда', 'verbose_name_plural': 'Еда'},
        ),
        migrations.AlterModelOptions(
            name='menu',
            options={'verbose_name': 'Меню', 'verbose_name_plural': 'Меню'},
        ),
    ]
