# Generated by Django 4.0.6 on 2022-11-26 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_app', '0003_alter_food_options_alter_menu_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='title',
            field=models.CharField(default=1, max_length=255, verbose_name='Название'),
            preserve_default=False,
        ),
    ]
