# Generated by Django 4.0.6 on 2022-12-10 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_app', '0006_cookers_galery'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cookers',
            options={'verbose_name': 'Повар', 'verbose_name_plural': 'Повара'},
        ),
        migrations.AlterModelOptions(
            name='galery',
            options={'verbose_name': 'Галерея', 'verbose_name_plural': 'Галереи'},
        ),
        migrations.AddField(
            model_name='cookers',
            name='description',
            field=models.CharField(default=1, max_length=150, verbose_name='Описание'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cookers',
            name='first_name',
            field=models.CharField(max_length=255, null=True, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='cookers',
            name='last_name',
            field=models.CharField(max_length=255, null=True, verbose_name='Фамилия'),
        ),
    ]
